# Generated by Django 2.0.6 on 2018-06-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('topic', models.CharField(max_length=50, verbose_name='Topic')),
                ('important_points', models.CharField(max_length=500, verbose_name='Important Points')),
                ('examples', models.CharField(max_length=500, verbose_name='Relevant Examples')),
            ],
            options={
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('topic', models.CharField(max_length=50, verbose_name='Topic')),
                ('topics_covered', models.CharField(max_length=500, verbose_name='Topics Covered')),
                ('number_of_topics_covered', models.IntegerField(verbose_name='Number Of Topics covered')),
                ('examples_for_covered_topics', models.CharField(blank=True, max_length=500, verbose_name='Examples of covered topics')),
                ('topics_not_covered', models.CharField(max_length=500, verbose_name='Topics not covered')),
                ('percentage_covered', models.IntegerField(verbose_name='Percentage Completion')),
                ('intensity', models.IntegerField(verbose_name='Audio Intensity')),
            ],
            options={
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=50, verbose_name='Facaulty')),
                ('semester', models.CharField(max_length=50, verbose_name='Semester')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('topic', models.CharField(max_length=50, verbose_name='Topic')),
                ('sesion_topic', models.CharField(max_length=2000, verbose_name='Session Topic')),
            ],
            options={
                'verbose_name_plural': 'Sessions',
            },
        ),
    ]
