# Generated by Django 2.0.6 on 2018-06-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='intensity',
            field=models.IntegerField(blank=True, verbose_name='Audio Intensity'),
        ),
    ]
